# Generated by Django 5.1.3 on 2025-08-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_options_alter_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="has_variants",
            field=models.BooleanField(default=False),
        ),
    ]
