# Generated by Django 5.1.3 on 2025-08-01 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_has_variants"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="has_variants",
        ),
    ]
