# Generated by Django 5.1.3 on 2025-08-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="product_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
