# Generated by Django 5.1.3 on 2025-08-08 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_flashdeal"),
    ]

    operations = [
        migrations.AddField(
            model_name="flashdeal",
            name="title",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
